version: "3.9"
services:
  frontend:
    build: ./react-frontend
    #image: pavanvere/frontend:0.0.1  # or 0.0.17 #docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' springboot
    container_name: react      #127 image 1 # image public ip # image3 localhost # image4 container name
    stdin_open: true
    environment: 
      - REACT_APP_API_URL=http://localhost:8082/api/v1/employees
      #BACKEND_API: localhost
    ports:
      - "3001:3000"
    depends_on:
      - mongo
      - springboot

  springboot:
    build: ./springboot-mongodb-crud-example
    #image: pavanvere/springboot:0.0.1
    container_name: springboot
    environment:
      DB_SERVER: mongo
      #MONGO_URL: mongodb://mongo:27017/EmployeeDB
    ports:
    - "8082:8080"
    depends_on:
      - mongo

  mongo:
    image: mongo
    container_name: mongo
    ports:
    - "27017:27017"